baseURL = 'https://chnyutao.github.io/'
disableKinds = ['taxonomy']
enableGitInfo = true
languageCode = 'en-us'
title = 'Yutao Chen'

[markup.goldmark.renderer]
unsafe = true

[[menus.main]]
name = "home"
url = "#"
weight = 1
[[menus.main]]
name = "about"
url = "#about"
weight = 2
[[menus.main]]
name = "news"
url = "#news"
weight = 3
[[menus.main]]
name = "publications"
url = "#publications"
weight = 4
[[menus.main]]
name = "résumé"
url = "https://drive.google.com/file/d/17O4CrllhZ79U-JA_kL00ufe_-d_25rHW"
weight = 5

[params]
author = 'Yutao Chen'
favicon = 'favicon.ico'

[params.personal]
avatar = 'avatar.jpg'
name = 'Yutao Chen'
title = 'PhD Student'
affiliation = """
Department of Computer and Information Science<br>
Faculty of Science and Technology<br>
University of Macau"""

[params.personal.social]
"1" = { name = "Email", icon = "at", link = "mailto:yutaochen@um.edu.mo" }
"2" = { name = "GitHub", icon = "github", link = "https://github.com/chnyutao" }
"3" = { name = "Google Scholar", icon = "google-scholar", link = "https://scholar.google.com/citations?user=bNs7ulQAAAAJ" }
"4" = { name = "Twitter", icon = "twitter", link = "https://x.com/chnyutao" }
